#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
            sleep 5
            echo "ifspeed started"
            . /etc/profile
	    cd /root/ifspeed
            ./run_ifspeed.sh &
}

stop() {
            killall run_ifspeed.sh
}
